baseURL = "https://www.adapostolidis.com"
title = "Apostolis Apostolidis"
#themesDir = "../.."
theme = "m10c"
paginate = 5

[params]
  author = "Apostolis D. Apostolidis"
  description = "Mathematics graduate turned Software Î•ngineer, based in Manchester, UK. Half Greek, half British. Citizen of Nowhere."
  homeTitle = "Welcome"
  [[params.social]]
    name = "github"
    url = "https://github.com/Apostolos-Daniel/"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/apostolis09/"

  # Green theme
  [params.style]
   darkestColor = "#315659"
   darkColor = "#253031"
   primaryColor = "#dad865"
   lightColor = "#96a879"
   lightestColor = "#fff"

  # Red and black theme
  #[params.style]
    # darkestColor = "#d35050"
    # darkColor = "#212121"
    # primaryColor = "#ffffff"
    # lightColor = "#a2a2a2"
    # lightestColor = "#d3d3d3"

[menu]
  [[menu.main]]
    name = "home"
    #post = "<span class='alert'>New!</span>"
    #pre = "<i class='fa fa-road'></i>"
    url = "/"
    weight = 1

  # [[menu.main]]
  #   name = "bio"
  #   #post = "<span class='alert'>New!</span>"
  #   #pre = "<i class='fa fa-road'></i>"
  #   url = "/bio/"
  #   weight = 1000

  # [[menu.main]]
  #   name = "projects"
  #   #pre = "<i class='fa fa-heart'></i>"
  #   url = "/project/"
  #   weight = 10000

  [[menu.main]]
    name = "blog"
    #post = "<span class='alert'>New!</span>"
    #pre = "<i class='fa fa-road'></i>"
    url = "/post/"
    weight = 20000

  [[menu.main]]
    name = "contact"
    #pre = "<i class='fa fa-heart'></i>"
    url = "/contact/"
    weight = 25000