baseurl = "http://www.example.com"
title = "apostolis apostolidis"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "apostolis"

[params]
    author = "Apostolis Apostolidis"
    description = "Apostoli's personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack Software Engineer"
    avatarurl = "images/avatar.jpg"
    footercontent = "Enter a text here."

    dateformat = "March 10, 2019"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Apostolos-Daniel/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/apostolis09/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/apostolosapostolidis/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@tolisapostolidis"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"


    [languages.gr-br]
        languagename = "Ελληνικά"
        title = "Αποστόλος Αποστολίδης"

        [languages.gr-br.params]
            author = "João Ninguém"
            info = "Full Stack DevOps e Mágico"
            description = "Sítio pessoal de João Ninguém"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "Coloque algum texto aqui."

        [languages.gr-br.menu]

            [[languages.gr-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "/pt-br/about/"

            [[languages.gr-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "/pt-br/posts/"

            [[languages.gr-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "/pt-br/projects/"

            [[languages.gr-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "/pt-br/contact/"
