baseURL = "https://www.adapostolidis.com"
title = "Apostolis Apostolidis"
#themesDir = "../.."
theme = "m10c"
paginate = 5

[params]
  author = "Apostolis D. Apostolidis"
  description = "A mathematics graduate turned Software Engineer"
  [[params.social]]
    name = "github"
    url = "https://github.com/Apostolos-Daniel/"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/apostolis09/"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    primaryColor = "#ffffff"
    lightColor = "#a2a2a2"
    lightestColor = "#d3d3d3"
